// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

type RecentProject = import("./types/project-history").RecentProject;
type CodexAgentSession = import("./types/codex-bridge").CodexAgentSession;
type CodexEventPayload = import("./types/codex-bridge").CodexEventPayload;
type CodexRequestPayload = import("./types/codex-bridge").CodexRequestPayload;
type CodexRequestResponse = import("./types/codex-bridge").CodexRequestResponse;
type CodexSessionReadyPayload = import("./types/codex-bridge").CodexSessionReadyPayload;
type EditorOpenFilePayload = import("./types/codex-bridge").EditorOpenFilePayload;

interface Window {
  api: {
    openFolder: () => Promise<string | null>;
    openProject: (folderPath: string) => Promise<void>;
    getEditorFolder: () => Promise<string | null>;
    getRecentProjects: () => Promise<RecentProject[]>;
    removeRecentProject: (projectPath: string) => Promise<RecentProject[]>;
    onEditorFolder: (
      callback: (folderPath: string) => void
    ) => () => void;
    readDirectory: (
      folderPath: string
    ) => Promise<import("./types/file-tree").FileNode | null>;
    readFile: (filePath: string) => Promise<string>;
    writeFile: (filePath: string, content: string) => Promise<void>;
    createFile: (parentPath: string, name: string) => Promise<string>;
    createFolder: (parentPath: string, name: string) => Promise<string>;
    rename: (targetPath: string, newName: string) => Promise<string>;
    delete: (targetPath: string) => Promise<void>;
    move: (sourcePath: string, destinationFolder: string) => Promise<string>;
    listFiles: (rootPath: string) => Promise<string[]>;
    minimizeWindow: () => Promise<void>;
    toggleMaximizeWindow: () => Promise<void>;
    closeWindow: () => Promise<void>;
  };
  codex: {
    ensureAgent: (agentId: string, cwd: string) => Promise<CodexAgentSession>;
    killAgent: (agentId: string) => Promise<void>;
    listAgents: () => Promise<string[]>;
    onEvent: (callback: (payload: CodexEventPayload) => void) => () => void;
    onRequest: (
      callback: (payload: CodexRequestPayload) => void
    ) => () => void;
    respondToRequest: (response: CodexRequestResponse) => Promise<void>;
    sendMessage: (
      agentId: string,
      text: string,
      model?: string | null,
      collaborationMode?: string | null,
      approvalPolicy?: string | null,
      effort?: string | null,
      attachments?: string[]
    ) => Promise<void>;
    createSession: (sessionId: string, cwd: string) => Promise<CodexAgentSession>;
    rpcCall: (agentId: string, method: string, params: unknown) => Promise<unknown>;
    interruptTurn: (agentId: string, threadId: string, turnId: string) => Promise<unknown>;
    steerTurn: (
      agentId: string,
      threadId: string,
      input: unknown[],
      expectedTurnId: string
    ) => Promise<unknown>;
    onSessionReady: (
      callback: (payload: CodexSessionReadyPayload) => void
    ) => () => void;
  };
  editor: {
    openFile: (payload: EditorOpenFilePayload) => Promise<void>;
    onOpenFile: (callback: (payload: EditorOpenFilePayload) => void) => () => void;
    onFileChanged: (callback: (payload: { path: string }) => void) => () => void;
  };
}
